# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'yingKe' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'AFNetworking', '~> 3.1.0'
      pod 'Masonry', '~> 1.0.1'
         pod 'SDWebImage', '~> 3.8.1'

  # Pods for yingKe

end
